export interface MeetingPlace {
  name: string;
  placeUrl: string;
  kakaoMapId: number;
  latitude: number;
  longitude: number;
}

export interface MeetingInfo {
  id: number;
  title: string;
  description: string;
  category: string;
  meetingPlace: MeetingPlace;
  participantLimit: number;
  rule: string;
  joinQuestion: string;
  schedule: string;
  level: string;
  minimumAge: number;
  maximumAge: number;
  maleRatio: number;
  femaleRatio: number;
  hasMembershipFee: boolean;
  membershipFee: number;
  hobby: string;
}

const joggingData: MeetingInfo[] = [
  {
    id: 1,
    title: '조깅 모임 1',
    description: '한강공원에서 함께 조깅해요!',
    category: 'SPORTS',
    meetingPlace: {
      name: '한강공원',
      placeUrl: 'https://maps.example.com/hangangpark',
      kakaoMapId: 123456789,
      latitude: 37.570379,
      longitude: 126.991287,
    },
    participantLimit: 15,
    rule: '시간 엄수 부탁드립니다.',
    joinQuestion: '이 모임에 참여하고 싶은 이유는 무엇인가요?',
    schedule: '2024-08-01T18:00:00',
    level: 'BEGINNER',
    minimumAge: 18,
    maximumAge: 50,
    maleRatio: 50,
    femaleRatio: 50,
    hasMembershipFee: false,
    membershipFee: 0,
    hobby: '조깅',
  },
  {
    id: 2,
    title: '조깅 모임 2',
    description: '조깅 후 스트레칭도 함께해요.',
    category: 'SPORTS',
    meetingPlace: {
      name: '성동구 조깅 코스',
      placeUrl: 'https://maps.example.com/seongdong',
      kakaoMapId: 987654321,
      latitude: 37.5503,
      longitude: 127.0408,
    },
    participantLimit: 12,
    rule: '시간 엄수 부탁드립니다.',
    joinQuestion: '이 모임에 참여하고 싶은 이유는 무엇인가요?',
    schedule: '2024-08-03T07:00:00',
    level: 'BEGINNER',
    minimumAge: 18,
    maximumAge: 50,
    maleRatio: 50,
    femaleRatio: 50,
    hasMembershipFee: true,
    membershipFee: 5000,
    hobby: '조깅',
  },
  {
    id: 3,
    title: '조깅 모임 3',
    description: '아침 조깅으로 상쾌한 하루 시작!',
    category: 'SPORTS',
    meetingPlace: {
      name: '성북구 조깅 코스',
      placeUrl: 'https://maps.example.com/seongbuk',
      kakaoMapId: 456789123,
      latitude: 37.5894,
      longitude: 127.0164,
    },
    participantLimit: 20,
    rule: '시간 엄수 부탁드립니다.',
    joinQuestion: '이 모임에 참여하고 싶은 이유는 무엇인가요?',
    schedule: '2024-08-05T06:00:00',
    level: 'BEGINNER',
    minimumAge: 18,
    maximumAge: 50,
    maleRatio: 50,
    femaleRatio: 50,
    hasMembershipFee: false,
    membershipFee: 0,
    hobby: '조깅',
  },
  {
    id: 4,
    title: '조깅 모임 4',
    description: '한강 야경을 보며 조깅해요.',
    category: 'SPORTS',
    meetingPlace: {
      name: '서초구 조깅 코스',
      placeUrl: 'https://maps.example.com/seocho',
      kakaoMapId: 234567891,
      latitude: 37.4838,
      longitude: 127.0324,
    },
    participantLimit: 15,
    rule: '시간 엄수 부탁드립니다.',
    joinQuestion: '이 모임에 참여하고 싶은 이유는 무엇인가요?',
    schedule: '2024-08-07T20:00:00',
    level: 'BEGINNER',
    minimumAge: 18,
    maximumAge: 50,
    maleRatio: 50,
    femaleRatio: 50,
    hasMembershipFee: true,
    membershipFee: 5000,
    hobby: '조깅',
  },
  {
    id: 5,
    title: '조깅 모임 5',
    description: '주말 오전 조깅, 함께해요!',
    category: 'SPORTS',
    meetingPlace: {
      name: '송파구 조깅 코스',
      placeUrl: 'https://maps.example.com/songpa',
      kakaoMapId: 345678912,
      latitude: 37.5143,
      longitude: 127.1067,
    },
    participantLimit: 10,
    rule: '시간 엄수 부탁드립니다.',
    joinQuestion: '이 모임에 참여하고 싶은 이유는 무엇인가요?',
    schedule: '2024-08-10T08:00:00',
    level: 'BEGINNER',
    minimumAge: 18,
    maximumAge: 50,
    maleRatio: 50,
    femaleRatio: 50,
    hasMembershipFee: false,
    membershipFee: 0,
    hobby: '조깅',
  },
  {
    id: 6,
    title: '조깅 모임 6',
    description: '저녁 조깅 후 간단한 간식 시간.',
    category: 'SPORTS',
    meetingPlace: {
      name: '강남구 조깅 코스',
      placeUrl: 'https://maps.example.com/gangnam',
      kakaoMapId: 567891234,
      latitude: 37.5172,
      longitude: 127.0473,
    },
    participantLimit: 12,
    rule: '시간 엄수 부탁드립니다.',
    joinQuestion: '이 모임에 참여하고 싶은 이유는 무엇인가요?',
    schedule: '2024-08-12T19:30:00',
    level: 'BEGINNER',
    minimumAge: 18,
    maximumAge: 50,
    maleRatio: 50,
    femaleRatio: 50,
    hasMembershipFee: true,
    membershipFee: 5000,
    hobby: '조깅',
  },
  {
    id: 7,
    title: '조깅 모임 7',
    description: '건강한 조깅으로 체력 길러요!',
    category: 'SPORTS',
    meetingPlace: {
      name: '종로구 조깅 코스',
      placeUrl: 'https://maps.example.com/jongno',
      kakaoMapId: 678912345,
      latitude: 37.572,
      longitude: 126.9794,
    },
    participantLimit: 15,
    rule: '시간 엄수 부탁드립니다.',
    joinQuestion: '이 모임에 참여하고 싶은 이유는 무엇인가요?',
    schedule: '2024-08-14T17:30:00',
    level: 'BEGINNER',
    minimumAge: 18,
    maximumAge: 50,
    maleRatio: 50,
    femaleRatio: 50,
    hasMembershipFee: false,
    membershipFee: 0,
    hobby: '조깅',
  },
  {
    id: 8,
    title: '조깅 모임 8',
    description: '새벽 조깅으로 활기찬 하루!',
    category: 'SPORTS',
    meetingPlace: {
      name: '강북구 조깅 코스',
      placeUrl: 'https://maps.example.com/gangbuk',
      kakaoMapId: 789123456,
      latitude: 37.6407,
      longitude: 127.0253,
    },
    participantLimit: 10,
    rule: '시간 엄수 부탁드립니다.',
    joinQuestion: '이 모임에 참여하고 싶은 이유는 무엇인가요?',
    schedule: '2024-08-16T06:00:00',
    level: 'BEGINNER',
    minimumAge: 18,
    maximumAge: 50,
    maleRatio: 50,
    femaleRatio: 50,
    hasMembershipFee: true,
    membershipFee: 5000,
    hobby: '조깅',
  },
  {
    id: 9,
    title: '조깅 모임 9',
    description: '도심 속 조깅, 함께 달려요.',
    category: 'SPORTS',
    meetingPlace: {
      name: '중구 조깅 코스',
      placeUrl: 'https://maps.example.com/junggu',
      kakaoMapId: 891234567,
      latitude: 37.5636,
      longitude: 126.9977,
    },
    participantLimit: 18,
    rule: '시간 엄수 부탁드립니다.',
    joinQuestion: '이 모임에 참여하고 싶은 이유는 무엇인가요?',
    schedule: '2024-08-18T19:00:00',
    level: 'BEGINNER',
    minimumAge: 18,
    maximumAge: 50,
    maleRatio: 50,
    femaleRatio: 50,
    hasMembershipFee: false,
    membershipFee: 0,
    hobby: '조깅',
  },
  {
    id: 10,
    title: '조깅 모임 10',
    description: '한강변을 따라 함께 조깅해요.',
    category: 'SPORTS',
    meetingPlace: {
      name: '용산구 조깅 코스',
      placeUrl: 'https://maps.example.com/yongsan',
      kakaoMapId: 912345678,
      latitude: 37.5311,
      longitude: 126.9813,
    },
    participantLimit: 14,
    rule: '시간 엄수 부탁드립니다.',
    joinQuestion: '이 모임에 참여하고 싶은 이유는 무엇인가요?',
    schedule: '2024-08-20T18:30:00',
    level: 'BEGINNER',
    minimumAge: 18,
    maximumAge: 50,
    maleRatio: 50,
    femaleRatio: 50,
    hasMembershipFee: true,
    membershipFee: 5000,
    hobby: '조깅',
  },
];

export default joggingData;
